# cspell:ignore esbuild, unrs
packages:
  - apps/*
  - packages/*
  - tooling/*

allowUnusedPatches: false

catalog:
  "@babel/plugin-syntax-jsx": ^7.27.1
  "@babel/preset-typescript": ^7.28.5
  "@fontsource-variable/ibm-plex-sans": ^5.2.8
  "@types/node": ^24.9.2
  eslint: ^9.39.0
  fontaine: ^0.6.0
  babel-plugin-react-compiler: 19.1.0-rc.3
  typescript: ^5.9.3
  vite: npm:rolldown-vite@7.1.20
  vite-plugin-inspect: ^11.3.3
  "@vitejs/plugin-react": ^5.1.0
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.2
  "@stylexjs/babel-plugin": ^0.16.3
  "@stylexjs/eslint-plugin": ^0.16.3
  "@stylexjs/postcss-plugin": ^0.16.3
  "@stylexjs/stylex": ^0.16.3
  react: 19.3.0-canary-561ee24d-20251101
  react-dom: 19.3.0-canary-561ee24d-20251101
  tsc-alias: ^1.8.16

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver

overrides:
  eslint-import-resolver-typescript>eslint-plugin-import: "-"
  react: "catalog:"
  react-dom: "catalog:"

engineStrict: true
packageManagerStrictVersion: true
saveWorkspaceProtocol: true
linkWorkspacePackages: true
managePackageManagerVersions: false
verifyDepsBeforeRun: "error"
strictDepBuilds: true
