# cspell:ignore esbuild, unrs, msgpackr, subdeps, vitest
packages:
  - apps/*
  - packages/*
  - tooling/*

allowUnusedPatches: false

catalog:
  "@babel/plugin-syntax-jsx": ^7.28.6
  "@babel/preset-typescript": ^7.28.5
  "@effect/language-service": ^0.75.1
  "@effect/platform-node": 4.0.0-beta.10
  "@effect/sql-pg": 4.0.0-beta.10
  "@effect/vitest": 4.0.0-beta.10
  effect: 4.0.0-beta.10
  "@electric-sql/client": ^1.5.7
  "@fontsource-variable/ibm-plex-sans": ^5.2.8
  "@types/node": ^25.3.0
  eslint: ^9.39.2
  fontaine: ^0.8.0
  babel-plugin-react-compiler: 19.1.0-rc.3
  typescript: ^5.9.3
  vite: npm:rolldown-vite@7.3.1
  vitest: ^4.0.18
  vite-plugin-inspect: ^11.3.3
  "@vitejs/plugin-react": ^5.1.4
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@stylexjs/babel-plugin": ^0.17.5
  "@stylexjs/eslint-plugin": ^0.17.5
  "@stylexjs/postcss-plugin": ^0.17.5
  "@stylexjs/stylex": ^0.17.5
  react: v19.3.0-canary-2ba30655-20260219
  react-dom: v19.3.0-canary-2ba30655-20260219
  tsc-alias: ^1.8.16
  type-fest: ^5.4.4
  wait-on: ^9.0.4

allowBuilds:
  "@parcel/watcher": true
  unrs-resolver: true
  esbuild: false
  msgpackr-extract: false

overrides:
  "@effect/vitest>vitest": "catalog:"
  eslint-import-resolver-typescript>eslint-plugin-import: "-"
  react: "catalog:"
  react-dom: "catalog:"

patchedDependencies:
  "@babel/preset-typescript@7.28.5": patches/@babel__preset-typescript.patch
  prettier-plugin-sql@0.19.2: patches/prettier-plugin-sql.patch

engineStrict: true
packageManagerStrictVersion: true
saveWorkspaceProtocol: true
linkWorkspacePackages: true
managePackageManagerVersions: true
verifyDepsBeforeRun: "error"
strictDepBuilds: true
