# cspell:ignore esbuild, unrs, msgpackr, subdeps, vitest
packages:
  - apps/*
  - packages/*
  - tooling/*

allowUnusedPatches: false

catalog:
  "@babel/plugin-syntax-jsx": ^7.27.1
  "@babel/preset-typescript": ^7.28.5
  "@effect/cluster": ^0.56.1
  "@effect/experimental": ^0.58.0
  "@effect/language-service": ^0.64.1
  "@effect/opentelemetry": ^0.60.0
  "@effect/platform": ^0.94.1
  "@effect/platform-node": ^0.104.0
  "@effect/rpc": ^0.73.0
  "@effect/sql": ^0.49.0
  "@effect/sql-pg": ^0.50.1
  "@effect/workflow": ^0.16.0
  "@effect/vitest": ^0.27.0
  effect: ^3.19.14
  "@fontsource-variable/ibm-plex-sans": ^5.2.8
  "@types/node": ^25.0.3
  eslint: ^9.39.2
  fontaine: ^0.7.0
  babel-plugin-react-compiler: 19.1.0-rc.3
  typescript: ^5.9.3
  vite: npm:rolldown-vite@7.3.0
  vitest: ^4.0.16
  vite-plugin-inspect: ^11.3.3
  "@vitejs/plugin-react": ^5.1.2
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@stylexjs/babel-plugin": ^0.17.4
  "@stylexjs/eslint-plugin": ^0.17.4
  "@stylexjs/postcss-plugin": ^0.17.4
  "@stylexjs/stylex": ^0.17.4
  react: 19.3.0-canary-f93b9fd4-20251217
  react-dom: 19.3.0-canary-f93b9fd4-20251217
  tsc-alias: ^1.8.16
  wait-on: ^9.0.3

allowBuilds:
  "@parcel/watcher": true
  unrs-resolver: true
  esbuild: false
  msgpackr-extract: false

overrides:
  "@effect/vitest>vitest": "catalog:"
  eslint-import-resolver-typescript>eslint-plugin-import: "-"
  react: "catalog:"
  react-dom: "catalog:"

patchedDependencies:
  "@babel/preset-typescript@7.28.5": patches/@babel__preset-typescript.patch
  prettier-plugin-sql@0.19.2: patches/prettier-plugin-sql.patch

engineStrict: true
packageManagerStrictVersion: true
saveWorkspaceProtocol: true
linkWorkspacePackages: true
managePackageManagerVersions: true
verifyDepsBeforeRun: "error"
strictDepBuilds: true
