# cspell:ignore esbuild, unrs, msgpackr
packages:
  - apps/*
  - packages/*
  - tooling/*

allowUnusedPatches: false

catalog:
  "@effect/platform": ^0.93.6
  "@effect/platform-node": ^0.103.0
  "@effect/sql": ^0.48.6
  "@effect/sql-pg": ^0.49.7
  effect: ^3.19.9
  "@fontsource-variable/ibm-plex-sans": ^5.2.8
  "@types/node": ^24.10.1
  eslint: ^9.39.1
  fontaine: ^0.7.0
  babel-plugin-react-compiler: 19.1.0-rc.3
  typescript: ^5.9.3
  vite: npm:rolldown-vite@7.2.10
  vite-plugin-inspect: ^11.3.3
  "@vitejs/plugin-react": ^5.1.1
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@stylexjs/eslint-plugin": ^0.17.2
  "@stylexjs/stylex": ^0.17.2
  "@stylexjs/unplugin": ^0.17.2
  react: 19.3.0-canary-fd524fe0-20251121
  react-dom: 19.3.0-canary-fd524fe0-20251121
  tsc-alias: ^1.8.16
  wait-on: ^9.0.3

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver

ignoredBuiltDependencies:
  - msgpackr-extract

overrides:
  eslint-import-resolver-typescript>eslint-plugin-import: "-"
  react: "catalog:"
  react-dom: "catalog:"

patchedDependencies:
  prettier-plugin-sql: patches/prettier-plugin-sql.patch

engineStrict: true
packageManagerStrictVersion: true
saveWorkspaceProtocol: true
linkWorkspacePackages: true
managePackageManagerVersions: true
verifyDepsBeforeRun: "error"
strictDepBuilds: true
