# cspell:ignore esbuild, unrs, msgpackr, subdeps, vitest
packages:
  - apps/*
  - packages/*
  - tooling/*

allowBuilds:
  esbuild: false
  msgpackr-extract: true
  unrs-resolver: true

allowUnusedPatches: false

catalog:
  "@babel/core": "^7.29.0"
  "@babel/plugin-syntax-jsx": ^7.28.6
  "@babel/preset-typescript": ^7.28.5
  "@effect/ai-openai": 4.0.0-beta.31
  "@effect/language-service": ^0.80.0
  "@effect/platform-node": 4.0.0-beta.31
  "@effect/platform-node-shared": 4.0.0-beta.31
  "@effect/sql-pg": 4.0.0-beta.31
  "@effect/vitest": 4.0.0-beta.31
  "@electric-sql/client": ^1.5.12
  "@fontsource-variable/ibm-plex-sans": ^5.2.8
  "@rolldown/plugin-babel": ^0.2.1
  "@stylexjs/babel-plugin": ^0.18.1
  "@stylexjs/eslint-plugin": ^0.18.1
  "@stylexjs/postcss-plugin": ^0.18.1
  "@stylexjs/stylex": ^0.18.1
  "@types/node": ^25.5.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/devtools": ^0.1.0
  "@vitejs/plugin-react": ^6.0.1
  babel-plugin-react-compiler: 0.0.0-experimental-1371fcb-20260304
  effect: 4.0.0-beta.31
  eslint: ^9.39.2
  fontaine: ^0.8.0
  react: 19.3.0-canary-3bc2d414-20260304
  react-dom: 19.3.0-canary-3bc2d414-20260304
  tsc-alias: ^1.8.16
  type-fest: ^5.4.4
  typescript: ^5.9.3
  vite: ^8.0.0
  vitest: ^4.1.0
  wait-on: ^9.0.4

engineStrict: true
linkWorkspacePackages: true
managePackageManagerVersions: true

overrides:
  babel-plugin-react-compiler: "catalog:"
  eslint-import-resolver-typescript>eslint-plugin-import: "-"
  react: "catalog:"
  react-dom: "catalog:"
  vite: "catalog:"

packageManagerStrictVersion: true

patchedDependencies:
  "@babel/preset-typescript@7.28.5": patches/@babel__preset-typescript.patch
  prettier-plugin-sql@0.19.2: patches/prettier-plugin-sql.patch

saveWorkspaceProtocol: true
strictDepBuilds: true
verifyDepsBeforeRun: "error"
