# cspell:ignore esbuild, unrs, msgpackr
packages:
  - apps/*
  - packages/*
  - tooling/*

allowUnusedPatches: false

catalog:
  "@effect/platform": ^0.93.0
  "@effect/platform-node": ^0.100.0
  effect: ^3.19.3
  "@babel/plugin-syntax-jsx": ^7.27.1
  "@babel/preset-typescript": ^7.28.5
  "@fontsource-variable/ibm-plex-sans": ^5.2.8
  "@types/node": ^24.10.0
  eslint: ^9.39.1
  fontaine: ^0.7.0
  babel-plugin-react-compiler: 19.1.0-rc.3
  typescript: ^5.9.3
  vite: npm:rolldown-vite@7.2.4
  vite-plugin-inspect: ^11.3.3
  "@vitejs/plugin-react": ^5.1.0
  "@types/react": ^19.2.3
  "@types/react-dom": ^19.2.2
  "@stylexjs/babel-plugin": ^0.16.3
  "@stylexjs/eslint-plugin": ^0.16.3
  "@stylexjs/postcss-plugin": ^0.16.3
  "@stylexjs/stylex": ^0.16.3
  react: 19.3.0-canary-fa50caf5-20251107
  react-dom: 19.3.0-canary-fa50caf5-20251107
  tsc-alias: ^1.8.16

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver

ignoredBuiltDependencies:
  - msgpackr-extract

overrides:
  eslint-import-resolver-typescript>eslint-plugin-import: "-"
  react: "catalog:"
  react-dom: "catalog:"

engineStrict: true
packageManagerStrictVersion: true
saveWorkspaceProtocol: true
linkWorkspacePackages: true
managePackageManagerVersions: false
verifyDepsBeforeRun: "error"
strictDepBuilds: true
trustPolicy: no-downgrade
