/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as AppRouteImport } from './routes/app.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'
import { Route as AppIndexRouteImport } from './routes/app.index.tsx'
import { Route as AppSettingsRouteImport } from './routes/app.settings.tsx'
import { Route as HomeChar123languageChar125RouteImport } from './routes/_home.{$language}.tsx'
import { Route as HomeChar123languageChar125IndexRouteImport } from './routes/_home.{$language}.index.tsx'
import { Route as ApiShapeChar123shapeNameChar125RouteImport } from './routes/api.shape.{$shapeName}.tsx'
import { Route as HomeChar123languageChar125SignUpRouteImport } from './routes/_home.{$language}.sign-up.tsx'
import { Route as HomeChar123languageChar125SignInRouteImport } from './routes/_home.{$language}.sign-in.tsx'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const HomeChar123languageChar125Route =
  HomeChar123languageChar125RouteImport.update({
    id: '/_home/{$language}',
    path: '/{$language}',
    getParentRoute: () => rootRouteImport,
  } as any)
const HomeChar123languageChar125IndexRoute =
  HomeChar123languageChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HomeChar123languageChar125Route,
  } as any)
const ApiShapeChar123shapeNameChar125Route =
  ApiShapeChar123shapeNameChar125RouteImport.update({
    id: '/api/shape/{$shapeName}',
    path: '/api/shape/{$shapeName}',
    getParentRoute: () => rootRouteImport,
  } as any)
const HomeChar123languageChar125SignUpRoute =
  HomeChar123languageChar125SignUpRouteImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => HomeChar123languageChar125Route,
  } as any)
const HomeChar123languageChar125SignInRoute =
  HomeChar123languageChar125SignInRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => HomeChar123languageChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/{$language}': typeof HomeChar123languageChar125RouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/{$language}/sign-in': typeof HomeChar123languageChar125SignInRoute
  '/{$language}/sign-up': typeof HomeChar123languageChar125SignUpRoute
  '/api/shape/{$shapeName}': typeof ApiShapeChar123shapeNameChar125Route
  '/{$language}/': typeof HomeChar123languageChar125IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/{$language}/sign-in': typeof HomeChar123languageChar125SignInRoute
  '/{$language}/sign-up': typeof HomeChar123languageChar125SignUpRoute
  '/api/shape/{$shapeName}': typeof ApiShapeChar123shapeNameChar125Route
  '/{$language}': typeof HomeChar123languageChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/_home/{$language}': typeof HomeChar123languageChar125RouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/_home/{$language}/sign-in': typeof HomeChar123languageChar125SignInRoute
  '/_home/{$language}/sign-up': typeof HomeChar123languageChar125SignUpRoute
  '/api/shape/{$shapeName}': typeof ApiShapeChar123shapeNameChar125Route
  '/_home/{$language}/': typeof HomeChar123languageChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/{$language}'
    | '/app/settings'
    | '/app/'
    | '/{$language}/sign-in'
    | '/{$language}/sign-up'
    | '/api/shape/{$shapeName}'
    | '/{$language}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/settings'
    | '/app'
    | '/{$language}/sign-in'
    | '/{$language}/sign-up'
    | '/api/shape/{$shapeName}'
    | '/{$language}'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/_home/{$language}'
    | '/app/settings'
    | '/app/'
    | '/_home/{$language}/sign-in'
    | '/_home/{$language}/sign-up'
    | '/api/shape/{$shapeName}'
    | '/_home/{$language}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HomeChar123languageChar125Route: typeof HomeChar123languageChar125RouteWithChildren
  ApiShapeChar123shapeNameChar125Route: typeof ApiShapeChar123shapeNameChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_home/{$language}': {
      id: '/_home/{$language}'
      path: '/{$language}'
      fullPath: '/{$language}'
      preLoaderRoute: typeof HomeChar123languageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/{$language}/': {
      id: '/_home/{$language}/'
      path: '/'
      fullPath: '/{$language}/'
      preLoaderRoute: typeof HomeChar123languageChar125IndexRouteImport
      parentRoute: typeof HomeChar123languageChar125Route
    }
    '/api/shape/{$shapeName}': {
      id: '/api/shape/{$shapeName}'
      path: '/api/shape/{$shapeName}'
      fullPath: '/api/shape/{$shapeName}'
      preLoaderRoute: typeof ApiShapeChar123shapeNameChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/{$language}/sign-up': {
      id: '/_home/{$language}/sign-up'
      path: '/sign-up'
      fullPath: '/{$language}/sign-up'
      preLoaderRoute: typeof HomeChar123languageChar125SignUpRouteImport
      parentRoute: typeof HomeChar123languageChar125Route
    }
    '/_home/{$language}/sign-in': {
      id: '/_home/{$language}/sign-in'
      path: '/sign-in'
      fullPath: '/{$language}/sign-in'
      preLoaderRoute: typeof HomeChar123languageChar125SignInRouteImport
      parentRoute: typeof HomeChar123languageChar125Route
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface HomeChar123languageChar125RouteChildren {
  HomeChar123languageChar125SignInRoute: typeof HomeChar123languageChar125SignInRoute
  HomeChar123languageChar125SignUpRoute: typeof HomeChar123languageChar125SignUpRoute
  HomeChar123languageChar125IndexRoute: typeof HomeChar123languageChar125IndexRoute
}

const HomeChar123languageChar125RouteChildren: HomeChar123languageChar125RouteChildren =
  {
    HomeChar123languageChar125SignInRoute:
      HomeChar123languageChar125SignInRoute,
    HomeChar123languageChar125SignUpRoute:
      HomeChar123languageChar125SignUpRoute,
    HomeChar123languageChar125IndexRoute: HomeChar123languageChar125IndexRoute,
  }

const HomeChar123languageChar125RouteWithChildren =
  HomeChar123languageChar125Route._addFileChildren(
    HomeChar123languageChar125RouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HomeChar123languageChar125Route: HomeChar123languageChar125RouteWithChildren,
  ApiShapeChar123shapeNameChar125Route: ApiShapeChar123shapeNameChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
