/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as AppRouteImport } from './routes/app.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'
import { Route as AppChatRouteImport } from './routes/app._chat.tsx'
import { Route as HomeChar123languageChar125RouteImport } from './routes/_home.{$language}.tsx'
import { Route as AppChatIndexRouteImport } from './routes/app._chat.index.tsx'
import { Route as HomeChar123languageChar125IndexRouteImport } from './routes/_home.{$language}.index.tsx'
import { Route as AppChatSettingsRouteImport } from './routes/app._chat.settings.tsx'
import { Route as ApiShapeChar123shapeNameChar125RouteImport } from './routes/api.shape.{$shapeName}.tsx'
import { Route as HomeChar123languageChar125SignUpRouteImport } from './routes/_home.{$language}.sign-up.tsx'
import { Route as HomeChar123languageChar125SignInRouteImport } from './routes/_home.{$language}.sign-in.tsx'
import { Route as AppChatConversationConversationIdRouteImport } from './routes/app._chat.conversation.$conversationId.tsx'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => AppRoute,
} as any)
const HomeChar123languageChar125Route =
  HomeChar123languageChar125RouteImport.update({
    id: '/_home/{$language}',
    path: '/{$language}',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRoute,
} as any)
const HomeChar123languageChar125IndexRoute =
  HomeChar123languageChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HomeChar123languageChar125Route,
  } as any)
const AppChatSettingsRoute = AppChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppChatRoute,
} as any)
const ApiShapeChar123shapeNameChar125Route =
  ApiShapeChar123shapeNameChar125RouteImport.update({
    id: '/api/shape/{$shapeName}',
    path: '/api/shape/{$shapeName}',
    getParentRoute: () => rootRouteImport,
  } as any)
const HomeChar123languageChar125SignUpRoute =
  HomeChar123languageChar125SignUpRouteImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => HomeChar123languageChar125Route,
  } as any)
const HomeChar123languageChar125SignInRoute =
  HomeChar123languageChar125SignInRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => HomeChar123languageChar125Route,
  } as any)
const AppChatConversationConversationIdRoute =
  AppChatConversationConversationIdRouteImport.update({
    id: '/conversation/$conversationId',
    path: '/conversation/$conversationId',
    getParentRoute: () => AppChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppChatRouteWithChildren
  '/{$language}': typeof HomeChar123languageChar125RouteWithChildren
  '/{$language}/sign-in': typeof HomeChar123languageChar125SignInRoute
  '/{$language}/sign-up': typeof HomeChar123languageChar125SignUpRoute
  '/api/shape/{$shapeName}': typeof ApiShapeChar123shapeNameChar125Route
  '/app/settings': typeof AppChatSettingsRoute
  '/{$language}/': typeof HomeChar123languageChar125IndexRoute
  '/app/': typeof AppChatIndexRoute
  '/app/conversation/$conversationId': typeof AppChatConversationConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppChatIndexRoute
  '/{$language}/sign-in': typeof HomeChar123languageChar125SignInRoute
  '/{$language}/sign-up': typeof HomeChar123languageChar125SignUpRoute
  '/api/shape/{$shapeName}': typeof ApiShapeChar123shapeNameChar125Route
  '/app/settings': typeof AppChatSettingsRoute
  '/{$language}': typeof HomeChar123languageChar125IndexRoute
  '/app/conversation/$conversationId': typeof AppChatConversationConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/_home/{$language}': typeof HomeChar123languageChar125RouteWithChildren
  '/app/_chat': typeof AppChatRouteWithChildren
  '/_home/{$language}/sign-in': typeof HomeChar123languageChar125SignInRoute
  '/_home/{$language}/sign-up': typeof HomeChar123languageChar125SignUpRoute
  '/api/shape/{$shapeName}': typeof ApiShapeChar123shapeNameChar125Route
  '/app/_chat/settings': typeof AppChatSettingsRoute
  '/_home/{$language}/': typeof HomeChar123languageChar125IndexRoute
  '/app/_chat/': typeof AppChatIndexRoute
  '/app/_chat/conversation/$conversationId': typeof AppChatConversationConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/{$language}'
    | '/{$language}/sign-in'
    | '/{$language}/sign-up'
    | '/api/shape/{$shapeName}'
    | '/app/settings'
    | '/{$language}/'
    | '/app/'
    | '/app/conversation/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/{$language}/sign-in'
    | '/{$language}/sign-up'
    | '/api/shape/{$shapeName}'
    | '/app/settings'
    | '/{$language}'
    | '/app/conversation/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/_home/{$language}'
    | '/app/_chat'
    | '/_home/{$language}/sign-in'
    | '/_home/{$language}/sign-up'
    | '/api/shape/{$shapeName}'
    | '/app/_chat/settings'
    | '/_home/{$language}/'
    | '/app/_chat/'
    | '/app/_chat/conversation/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HomeChar123languageChar125Route: typeof HomeChar123languageChar125RouteWithChildren
  ApiShapeChar123shapeNameChar125Route: typeof ApiShapeChar123shapeNameChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_chat': {
      id: '/app/_chat'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_home/{$language}': {
      id: '/_home/{$language}'
      path: '/{$language}'
      fullPath: '/{$language}'
      preLoaderRoute: typeof HomeChar123languageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_chat/': {
      id: '/app/_chat/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_home/{$language}/': {
      id: '/_home/{$language}/'
      path: '/'
      fullPath: '/{$language}/'
      preLoaderRoute: typeof HomeChar123languageChar125IndexRouteImport
      parentRoute: typeof HomeChar123languageChar125Route
    }
    '/app/_chat/settings': {
      id: '/app/_chat/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppChatSettingsRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/api/shape/{$shapeName}': {
      id: '/api/shape/{$shapeName}'
      path: '/api/shape/{$shapeName}'
      fullPath: '/api/shape/{$shapeName}'
      preLoaderRoute: typeof ApiShapeChar123shapeNameChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/{$language}/sign-up': {
      id: '/_home/{$language}/sign-up'
      path: '/sign-up'
      fullPath: '/{$language}/sign-up'
      preLoaderRoute: typeof HomeChar123languageChar125SignUpRouteImport
      parentRoute: typeof HomeChar123languageChar125Route
    }
    '/_home/{$language}/sign-in': {
      id: '/_home/{$language}/sign-in'
      path: '/sign-in'
      fullPath: '/{$language}/sign-in'
      preLoaderRoute: typeof HomeChar123languageChar125SignInRouteImport
      parentRoute: typeof HomeChar123languageChar125Route
    }
    '/app/_chat/conversation/$conversationId': {
      id: '/app/_chat/conversation/$conversationId'
      path: '/conversation/$conversationId'
      fullPath: '/app/conversation/$conversationId'
      preLoaderRoute: typeof AppChatConversationConversationIdRouteImport
      parentRoute: typeof AppChatRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatSettingsRoute: typeof AppChatSettingsRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppChatConversationConversationIdRoute: typeof AppChatConversationConversationIdRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatSettingsRoute: AppChatSettingsRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppChatConversationConversationIdRoute:
    AppChatConversationConversationIdRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface HomeChar123languageChar125RouteChildren {
  HomeChar123languageChar125SignInRoute: typeof HomeChar123languageChar125SignInRoute
  HomeChar123languageChar125SignUpRoute: typeof HomeChar123languageChar125SignUpRoute
  HomeChar123languageChar125IndexRoute: typeof HomeChar123languageChar125IndexRoute
}

const HomeChar123languageChar125RouteChildren: HomeChar123languageChar125RouteChildren =
  {
    HomeChar123languageChar125SignInRoute:
      HomeChar123languageChar125SignInRoute,
    HomeChar123languageChar125SignUpRoute:
      HomeChar123languageChar125SignUpRoute,
    HomeChar123languageChar125IndexRoute: HomeChar123languageChar125IndexRoute,
  }

const HomeChar123languageChar125RouteWithChildren =
  HomeChar123languageChar125Route._addFileChildren(
    HomeChar123languageChar125RouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HomeChar123languageChar125Route: HomeChar123languageChar125RouteWithChildren,
  ApiShapeChar123shapeNameChar125Route: ApiShapeChar123shapeNameChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
