name: 🧑‍🔬 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

permissions:
  contents: read

jobs:
  verify:
    name: 🔬 Verify
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run
        run: pnpm turbo run build lint typecheck sort-package-json spellcheck format test effect-diagnostics --continue

  boundaries:
    name: 🛂 Boundaries
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run
        run: pnpm turbo boundaries

  codegen:
    name: ⚙️ Codegen
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run
        run: pnpm codegen

      - name: Verify
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "❌ ERROR: Uncommitted changes detected after executing codegen"
            echo "💡 The following files were modified:"
            git status --porcelain
            echo "✨ Make sure to run all codegen tasks before committing and push all up-to-date files"
            exit 1
          fi
